### PR TITLE
974 low contrast andi

### PR DESCRIPTION
**Pull request by nicholas-goodwin**
## Description

- Removed Low Contrast Error from ANDI
- ...

## Reminders:
- [x] Be mindful of impacts of changing Major/Minor/Patch versions of each elixir app
- - [x] If updating patch version, are you sure there are no chart changes required to maintain functionality? If so, you should bump minor version instead.
  - [x] If updating Major or Minor versions , did you update the sauron chart configuration? 
- [x] If changing elixir code in an "app", did you update the relevant version
      in `mix.exs`?
- [x] If altering an API endpoint, was the relevant postman collection updated?
  - [x] If a new version of `smart_city` is being used (new fields on a struct), were the relevant postman collections updated?

### CODE REVIEW

**Review by c-m-duncan — COMMENTED** [review]
How does this interact with other color schemes? Since we can enter arbitrary colors

**Comment by nicholas-goodwin** [comment]
I would have to see how the branding side works, but there will be some changes to openshift-deploy to add the secondary, success, and error colors and plug it in.

**Review by ian-j-abbott-accenture — APPROVED** [review]

**Comment by nicholas-goodwin** [comment]
Okay, figured that out, will hold this PR until I get those changes in.

**Review by ian-j-abbott-accenture — CHANGES_REQUESTED** [review]
remove approval per request

**Review by ian-j-abbott-accenture — APPROVED** [review]

**Pull request merged**
