### PR TITLE
feat(789): whitelist img-src for andi logo

### PR DESCRIPTION
**Pull request by c-m-duncan**
## [Ticket Link #789](https://app.zenhub.com/workspaces/mdot-615b97c1a5fde400126174f8/issues/urbanos-public/internal/789)

Screen Recording 2022-09-20 at 3 40 52 PM

### CODE REVIEW

**Review by bmitchinson — APPROVED** [review]
Approved with the blocking comment that the mix version is updated.

We have to up the version with a patch, even for adjustments like this, to make sure images are built and pushed correctly when changes are merged.

**Comment by c-m-duncan** [comment]
I seem to be having some caching issues, changing my env still has the same content policy as before. Not sure how, since I'm restarting everything locally and doing a `Clear cache and hard reload`. Anyone have any ideas as to why / how it's happening?

**Comment by c-m-duncan** [comment]
> Approved with the blocking comment that the mix version is updated.
> 
> We have to up the version with a patch, even for adjustments like this, to make sure images are built and pushed correctly when changes are merged.

Ty, totally forgot about the version bump

**Comment by bmitchinson** [comment]
Due to recent merging, you'll need to update the mix version again

**Pull request merged**
